name: tgcalls_dart
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ffi: ^2.0.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  msix: ^3.9.1
  packagex: ^0.0.25
  test: ^1.21.0

msix_config: 
  display_name: tgcalls_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.tgcalls_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: tgcalls_dart
  dart_target: tgcalls_dart
  flutter_target: main
  dart_name: tgcalls_dart
  flutter_name: tgcalls_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
